// Gate 5K — T11 `finalizeVisit` (runtime-neutral TypeScript, no node:*
// imports).
//
// Implements the adopted single-transaction preflight + finalization contract
// of TRANSACTION-CONTRACTS-v1.md §11 / APPLICATION-CORE-v1.md §4.10 + §8:
//
//   * ONE explicit BEGIN IMMEDIATE … COMMIT/ROLLBACK unit — absolutely no
//     read-only preflight outside the authoritative transaction (no TOCTOU
//     window): re-read the Visit → Class-A idempotent branch → ALL preflight
//     SELECT checks inside the SAME transaction → structured blockers ⇒
//     ROLLBACK → guarded final UPDATE (changes == 1, B5) → COMMIT.
//
//   * Visit precondition (inside BEGIN IMMEDIATE): missing Visit ⇒
//     E_VISIT_NOT_FOUND; not finalized but status <> 'PREPARATION' ⇒
//     E_VISIT_NOT_PREPARATION. A finalized Visit (finalized_at IS NOT NULL
//     AND status IN ('COMPLETED','COMPLETED_WITH_UNINSPECTED')) is handled by
//     the Class-A retry branch FIRST — never treated as an illegal mutable
//     state, never reopened, never re-finalized. The impossible combination
//     finalized_at NOT NULL + status 'PREPARATION' is a typed
//     E_STATE_CONFLICT (schema CHECK makes it unrepresentable at rest; the
//     branch exists so a fabricated/corrupt read never silently converges).
//
//   * Preflight (all SELECTs inside the same transaction; blockers are
//     collected, never auto-fixed):
//       1. E_SCOPE_GAP — expected cell set == actual cell set, where
//          expected = captured universe × captured contexts, both
//          reconstructed ONLY from durable Visit rows (institution-context
//          rows with their pinned item_definition_id values; contexts =
//          institution context + every distinct subject context durably
//          present in the grid). Current ACTIVE definitions are never
//          queried to discover codes; no silent repair. Missing cells,
//          extra/mismatched cells, partial subject grids, version/context
//          mismatches and an empty captured universe all surface as
//          E_SCOPE_GAP.
//       2. E_UNRESOLVED_PENDING — any cell in the true unresolved pending
//          state (overlay_state='NOT_INSPECTED', answered_value_id NULL,
//          not_inspected_reason NULL) survives; includes unresolved
//          HUMAN_CONFIRMATION cells. No pending cell may survive
//          finalization.
//       3. E_UNINSPECTED_NEEDS_REASON — every deliberate NOT_INSPECTED cell
//          that will survive into the finalized Visit carries a meaningful
//          (trimmed non-blank) reason. Never auto-filled.
//       4. E_NC_UNACCOUNTED — every answered cell whose selected allowed
//          value has semantic_class='NON_COMPLIANT' is linked to a Finding
//          (finding_id IS NOT NULL). Re-check; never linked here.
//       5. E_NC_NEEDS_NOTE — every NON_COMPLIANT answered cell carries a
//          meaningful (trimmed non-blank) note. Re-check; never written here.
//       6. E_CHK012 — the adopted SCHEDULE physical/domain invariants
//          re-checked for every response whose PINNED definition has
//          response_model='SCHEDULE' (generic durable discriminator — never
//          item_code switching): reconciliation rows belong only to SCHEDULE
//          responses; no overlay state coexists with rows; COMPLIANT overall
//          has no discrepancy row (difference <> 0 OR discrepancy_type NOT
//          NULL); difference = observed_qty - declared_qty; discrepancy_type
//          from the closed set with OTHER ⇒ non-blank description; category
//          meaningful. Rows are never mutated by T11.
//       7. E_ORPHAN_FINDING — a Finding with origin_visit_id = this Visit,
//          status 'OPEN', and zero recorded sources across BOTH
//          checklist_response AND adhoc_observation. VOIDED findings are
//          EXPECTED source-less and are never blockers; OPEN/IN_TREATMENT/
//          RESOLVED findings and CorrectiveActions of ANY status are never
//          finalization blockers (remediation continues after field-truth
//          finalization) and are never transitioned/created/closed by T11.
//
//   * Blockers ⇒ ROLLBACK + ONE DomainError whose top-level code is the
//     FIRST blocker's code in the deterministic §8 order and whose
//     `blockers` payload carries EVERY blocker (codes + durable
//     identifiers/context: responseId / itemDefinitionId / subjectId /
//     itemCode / findingId / rowId + machine-readable `kind`). Ordering is
//     deterministic for repeatable tests/UI. No Arabic display prose is
//     generated by the domain; codes + identifiers are the source of truth.
//
//   * Final status derivation (inside the SAME transaction, from durable
//     Visit rows only — never caller-chosen): any checklist_response with
//     overlay_state='NOT_INSPECTED' ⇒ 'COMPLETED_WITH_UNINSPECTED', else
//     'COMPLETED'. NA never counts as NOT_INSPECTED; Finding/Action status
//     never influences the choice.
//
//   * Guarded final UPDATE (B5):
//       UPDATE visit SET status = <derived>, finalized_at = <normalized>
//        WHERE visit_id = ? AND status = 'PREPARATION' AND finalized_at IS NULL
//     requiring changes == 1. On changes != 1: ROLLBACK FIRST, then re-read
//     the durable Visit — a valid finalized row converges as Class-A
//     idempotent success (applied:false; the DURABLE status/finalized_at are
//     returned — a retry's fresh finalizedAt parameter never rewrites the
//     durable timestamp and never recalculates the final status); anything
//     else ⇒ E_STATE_CONFLICT. Never COMMIT after zero affected rows.
//
//   * finalizedAt: app-supplied strict ISO-8601 UTC instant (the exact
//     Gate-5G/5H/5J convention — YYYY-MM-DDTHH:MM:SS[.fraction]Z, explicit
//     'Z', calendar-valid components, no local/timezone-less/offset forms,
//     never invented internally, never permissive Date.parse). Trimmed before
//     validate/store; the trimmed text is stored verbatim.
//
// Out of scope (later gates): currentVisitState, Mission finalization,
// Finding/CorrectiveAction transitions, observation correction, report
// generation, Evidence, ExternalSystemTracking, UI/sync/mobile.

import type { SqlAdapter, SqlValue } from "../bootstrap/adapter.ts";
import { APP_ERR, DomainError, type AppErrorCode, type FinalizationBlocker } from "./errors.ts";
import { RECON_DISCREPANCY_TYPES } from "./initial-disposition.ts";

// ---------------------------------------------------------------------------
// public types
// ---------------------------------------------------------------------------

/** The two durable final Visit statuses — exactly the schema value set. */
export const VISIT_FINAL_STATUSES = ["COMPLETED", "COMPLETED_WITH_UNINSPECTED"] as const;
export type VisitFinalStatus = (typeof VISIT_FINAL_STATUSES)[number];

export interface FinalizeVisitInput {
    /** the durable key of the Visit (must exist; must be PREPARATION or already finalized) */
    visitId: number;
    /**
     * App-supplied strict ISO-8601 UTC instant
     * (`YYYY-MM-DDTHH:MM:SS[.fraction]Z`). Trimmed before validate/store;
     * the normalized trimmed text is stored verbatim. The final status is
     * NEVER caller-chosen — the service derives it from durable Visit rows.
     */
    finalizedAt: string;
}

export interface FinalizeVisitResult {
    /** false when the call converged on the already-applied durable final state (Class-A retry) */
    applied: boolean;
    visitId: number;
    /** the durable final status after the operation */
    status: VisitFinalStatus;
    /** the durable finalized_at (the normalized requested instant on apply; the existing durable one on retry) */
    finalizedAt: string;
}

// ---------------------------------------------------------------------------
// internal model
// ---------------------------------------------------------------------------

interface VisitSnapshot {
    visitId: number;
    status: string;
    finalizedAt: string | null;
}

/** thrown inside the write unit to force ROLLBACK + durable-state re-read (B5) */
class ZeroRowGuard extends Error {
    constructor() {
        super("guarded final visit update affected zero rows (B5)");
        this.name = "ZeroRowGuard";
    }
}

/** internal rollback marker: the preflight collected structured blockers */
class FinalizationBlocked extends Error {
    readonly blockers: readonly FinalizationBlocker[];

    constructor(blockers: readonly FinalizationBlocker[]) {
        super(`finalization blocked by ${blockers.length} blocker(s)`);
        this.name = "FinalizationBlocked";
        this.blockers = blockers;
    }
}

// ---------------------------------------------------------------------------
// normalization / validation helpers (Arabic never parsed)
// ---------------------------------------------------------------------------

/** trim; blank/missing => null. */
function normalizeText(v: string | null | undefined): string | null {
    if (v === null || v === undefined) return null;
    const t = v.trim();
    return t.length === 0 ? null : t;
}

function config(what: string): DomainError {
    return new DomainError(APP_ERR.CONFIG, `finalizeVisit: ${what}`);
}

/**
 * Strict ISO-8601 UTC validator — the exact Gate-5G/5H/5J convention
 * (OBS-1 recordedAt; src/application/observation-create.ts): runtime-neutral,
 * no permissive Date.parse (Date.parse would normalize impossible components
 * like 2026-02-30, month 13, or hour 25, which this contract rejects).
 *
 * Accepts exactly (after trimming): `YYYY-MM-DDTHH:MM:SS[.fraction]Z`
 *   - 4-digit year, real calendar month 01-12;
 *   - day valid for that month/year (leap years honored);
 *   - hour 00-23, minute 00-59, second 00-59;
 *   - optional dot-only fractional seconds (one or more digits);
 *   - the explicit UTC designator 'Z' is REQUIRED — a local/timezone-less
 *     datetime (`…T08:00:00`) or a numeric offset (`…+01:00`) is NOT UTC.
 * Returns the validated (trimmed) text, or null when invalid.
 */
function validateStrictUtcTimestamp(v: string): string | null {
    const m = /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.(\d+))?Z$/.exec(v);
    if (m === null) return null;
    const year = Number(m[1]);
    const month = Number(m[2]);
    const day = Number(m[3]);
    const hour = Number(m[4]);
    const minute = Number(m[5]);
    const second = Number(m[6]);
    if (month < 1 || month > 12) return null;
    if (hour > 23 || minute > 59 || second > 59) return null;
    const leap = year % 4 === 0 && (year % 100 !== 0 || year % 400 === 0);
    const daysInMonth = [31, leap ? 29 : 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];
    if (day < 1 || day > daysInMonth[month - 1]) return null;
    return v;
}

// ---------------------------------------------------------------------------
// service
// ---------------------------------------------------------------------------

export class VisitFinalizationService {
    private readonly db: SqlAdapter;

    constructor(db: SqlAdapter) {
        this.db = db;
    }

    /**
     * T11 — close the Visit's historical field truth in ONE atomic unit:
     * authoritative Visit read → idempotent finalized branch → ALL preflight
     * checks inside the SAME transaction → structured blockers ⇒ ROLLBACK →
     * derived-status guarded final UPDATE (changes == 1) → COMMIT.
     */
    async finalizeVisit(input: FinalizeVisitInput): Promise<FinalizeVisitResult> {
        const op = "finalizeVisit";
        const visitId = input.visitId;

        // pure request-shape validation only (nothing mutable is read here);
        // every authorization read happens inside the transaction below.
        // The timestamp is trimmed before validate/store — the stored text is
        // the normalized trimmed instant, never an invented internal clock.
        const finalizedAt = normalizeText(input.finalizedAt);
        if (finalizedAt === null) {
            throw config(`${op}: finalizedAt must be an app-supplied ISO-8601 UTC instant`);
        }
        if (validateStrictUtcTimestamp(finalizedAt) === null) {
            throw config(
                `${op}: finalizedAt must be a real ISO-8601 UTC instant in strict form ` +
                    "YYYY-MM-DDTHH:MM:SS[.fraction]Z (explicit 'Z'; no local / timezone-less / offset forms; " +
                    "calendar-valid components)",
            );
        }

        return this.runUnit(
            async () => {
                // 1) authoritative Visit read INSIDE BEGIN IMMEDIATE
                const visit = await this.readVisit(visitId, op);

                // 2) already finalized: the Class-A idempotent branch runs
                //    BEFORE any mutable-state treatment — never reopen, never
                //    rewrite finalized_at, never re-derive a final status.
                if (visit.finalizedAt !== null) {
                    if (visit.status === "COMPLETED" || visit.status === "COMPLETED_WITH_UNINSPECTED") {
                        return {
                            kind: "converged" as const,
                            result: {
                                applied: false,
                                visitId,
                                status: visit.status as VisitFinalStatus,
                                finalizedAt: visit.finalizedAt,
                            },
                        };
                    }
                    throw new DomainError(
                        APP_ERR.STATE_CONFLICT,
                        `${op}: visit ${visitId} carries finalized_at '${visit.finalizedAt}' but status ` +
                            `'${visit.status}' — a finalized Visit must hold a final status; this impossible ` +
                            "combination is a typed state/config conflict, never silent convergence",
                    );
                }
                if (visit.status !== "PREPARATION") {
                    throw new DomainError(
                        APP_ERR.VISIT_NOT_PREPARATION,
                        `${op}: visit ${visitId} is '${visit.status}' with finalized_at NULL; finalization ` +
                            "requires PREPARATION (a finalized Visit never reopens and never re-finalizes)",
                    );
                }

                // 3) run ALL finalization preflight SELECT checks inside this
                //    SAME transaction — the expected scope, pending cells,
                //    reasons, NC accountability/notes, SCHEDULE invariants and
                //    orphan findings are all read under the write lock, so no
                //    state may change between the validated snapshot and the
                //    guarded final UPDATE.
                const blockers = await this.runPreflight(visit);

                // 4) blockers => ROLLBACK + the complete structured blocker
                //    list (runUnit converts the marker into one DomainError
                //    carrying every blocker; the top-level code is the FIRST
                //    blocker's code in the deterministic §8 order).
                if (blockers.length > 0) {
                    throw new FinalizationBlocked(blockers);
                }

                // 5) final status derivation from durable Visit rows only —
                //    the caller can never choose it; Finding/Action status
                //    never influences it; NA never counts as NOT_INSPECTED.
                const hasNotInspected = await this.anyNotInspected(visit);
                const status: VisitFinalStatus = hasNotInspected ? "COMPLETED_WITH_UNINSPECTED" : "COMPLETED";

                // 6) guarded final UPDATE (B5) — one statement, changes == 1.
                const res = await this.db.run(
                    `UPDATE visit
                        SET status = ?, finalized_at = ?
                      WHERE visit_id = ? AND status = 'PREPARATION' AND finalized_at IS NULL`,
                    [status, finalizedAt, visitId] as readonly SqlValue[],
                );
                if (res.changes !== 1) throw new ZeroRowGuard();

                return {
                    kind: "applied" as const,
                    result: { applied: true, visitId, status, finalizedAt },
                };
            },
            async () => {
                // B5: the guarded final UPDATE changed != 1 rows ⇒ the whole
                // unit was rolled back; re-read the durable Visit. A valid
                // finalized row converges as Class-A idempotent success with
                // its DURABLE status/finalized_at (a fresh retry clock never
                // rewrites or recalculates them); anything else is a typed
                // conflict. Never COMMIT after zero affected rows.
                const durable = await this.readVisitIfPresent(visitId);
                if (
                    durable !== null &&
                    durable.finalizedAt !== null &&
                    (durable.status === "COMPLETED" || durable.status === "COMPLETED_WITH_UNINSPECTED")
                ) {
                    return {
                        kind: "converged" as const,
                        result: {
                            applied: false,
                            visitId,
                            status: durable.status as VisitFinalStatus,
                            finalizedAt: durable.finalizedAt,
                        },
                    };
                }
                throw new DomainError(
                    APP_ERR.STATE_CONFLICT,
                    `${op}: the guarded final UPDATE affected zero rows and the durable Visit is not a valid ` +
                        "finalized state — nothing was committed (B5)",
                );
            },
        ).then((outcome) => outcome.result);
    }

    // -- reads ----------------------------------------------------------------

    private async readVisitIfPresent(visitId: number): Promise<VisitSnapshot | null> {
        const rows = await this.db.query("SELECT status, finalized_at FROM visit WHERE visit_id = ?", [visitId]);
        if (rows.length === 0) return null;
        return {
            visitId,
            status: String(rows[0].status),
            finalizedAt: rows[0].finalized_at === null ? null : String(rows[0].finalized_at),
        };
    }

    private async readVisit(visitId: number, op: string): Promise<VisitSnapshot> {
        const visit = await this.readVisitIfPresent(visitId);
        if (visit === null) {
            throw new DomainError(APP_ERR.VISIT_NOT_FOUND, `${op}: visit ${visitId} does not exist`);
        }
        return visit;
    }

    // -- preflight (all SELECTs; never a write; deterministic ordering) --------

    /** ALL finalization checks in the authoritative APPLICATION-CORE §8 order. */
    private async runPreflight(visit: VisitSnapshot): Promise<FinalizationBlocker[]> {
        const blockers: FinalizationBlocker[] = [];
        blockers.push(...(await this.checkScopeGrid(visit)));
        blockers.push(...(await this.checkUnresolvedPending(visit)));
        blockers.push(...(await this.checkUninspectedReasons(visit)));
        blockers.push(...(await this.checkNcCells(visit)));
        blockers.push(...(await this.checkScheduleConsistency(visit)));
        blockers.push(...(await this.checkOrphanFindings(visit)));
        return blockers;
    }

    private blocker(
        code: AppErrorCode,
        kind: string,
        visitId: number,
        extra: Partial<FinalizationBlocker> = {},
    ): FinalizationBlocker {
        return { code, kind, visitId, ...extra };
    }

    /**
     * 1) E_SCOPE_GAP — exact-set equality between the expected cell set and
     * the actual row set, both derived ONLY from durable Visit state:
     *   expected = captured universe × captured contexts;
     *   captured universe = institution-context rows (subject_id IS NULL) and
     *     their pinned item_definition_id values (never a current-ACTIVE
     *     discovery, never silently repaired);
     *   captured contexts = the institution context + every distinct subject
     *     context durably present in the grid (rows reference them).
     * Missing cells, extra/mismatched cells (a subject-context row whose
     * pinned definition is outside the captured universe — a foreign/P1
     * definition or a different version — or a row in a non-captured
     * context), partial subject grids and an empty captured universe are all
     * blockers. (By definition the universe IS the institution-context row
     * set, so an institution-context row is never "extra" — it would enlarge
     * the universe itself; the adopted contract defines the expected set
     * from exactly those rows and no manifest/P0 comparison is invented
     * here.)
     * Order: missing cells by (context null-first/ascending, item_code);
     * extra cells by response_id.
     */
    private async checkScopeGrid(visit: VisitSnapshot): Promise<FinalizationBlocker[]> {
        const blockers: FinalizationBlocker[] = [];

        const universeRows = await this.db.query(
            `SELECT d.item_code, cr.item_definition_id
               FROM checklist_response cr
               JOIN checklist_item_definition d ON d.item_definition_id = cr.item_definition_id
              WHERE cr.visit_id = ? AND cr.subject_id IS NULL
              ORDER BY d.item_code, cr.response_id`,
            [visit.visitId],
        );
        if (universeRows.length === 0) {
            // the institution context is always in scope (§3.2) — an empty
            // captured universe makes the intended durable scope
            // unrecoverable; only reachable through out-of-band tampering.
            return [this.blocker(APP_ERR.SCOPE_GAP, "empty-captured-universe", visit.visitId)];
        }
        const universeDefs = universeRows.map((r) => ({
            itemDefinitionId: Number(r.item_definition_id),
            itemCode: String(r.item_code),
        }));

        const ctxRows = await this.db.query(
            `SELECT DISTINCT COALESCE(subject_id, 0) AS ctx
               FROM checklist_response
              WHERE visit_id = ?
              ORDER BY ctx`,
            [visit.visitId],
        );
        // 0 encodes the institution context (subject_id NULL), which is
        // guaranteed present whenever the universe is non-empty.
        const contexts: (number | null)[] = ctxRows.map((r) => (Number(r.ctx) === 0 ? null : Number(r.ctx)));

        const actualRows = await this.db.query(
            `SELECT cr.response_id, cr.item_definition_id, COALESCE(cr.subject_id, 0) AS ctx, d.item_code
               FROM checklist_response cr
               JOIN checklist_item_definition d ON d.item_definition_id = cr.item_definition_id
              WHERE cr.visit_id = ?`,
            [visit.visitId],
        );
        const actualKey = new Set(actualRows.map((r) => `${Number(r.item_definition_id)}|${Number(r.ctx)}`));

        // missing expected cells (deterministic: context null-first/ascending,
        // then item_code order)
        for (const subjectId of contexts) {
            const ctxKey = subjectId === null ? 0 : subjectId;
            for (const def of universeDefs) {
                if (!actualKey.has(`${def.itemDefinitionId}|${ctxKey}`)) {
                    blockers.push(
                        this.blocker(APP_ERR.SCOPE_GAP, "missing-cell", visit.visitId, {
                            itemDefinitionId: def.itemDefinitionId,
                            subjectId,
                            itemCode: def.itemCode,
                        }),
                    );
                }
            }
        }

        // extra / mismatched actual cells (deterministic: response_id order):
        // an actual cell whose pinned definition is NOT in the captured
        // universe (a foreign/P1 definition, a different version, an
        // out-of-scope context) makes actual != expected.
        const universeIdSet = new Set(universeDefs.map((d) => d.itemDefinitionId));
        const contextSet = new Set(contexts.map((s) => (s === null ? 0 : s)));
        for (const r of actualRows) {
            const defId = Number(r.item_definition_id);
            const ctx = Number(r.ctx);
            if (!universeIdSet.has(defId) || !contextSet.has(ctx)) {
                blockers.push(
                    this.blocker(APP_ERR.SCOPE_GAP, "extra-cell", visit.visitId, {
                        responseId: Number(r.response_id),
                        itemDefinitionId: defId,
                        subjectId: ctx === 0 ? null : ctx,
                        itemCode: String(r.item_code),
                    }),
                );
            }
        }
        return blockers;
    }

    /**
     * 2) E_UNRESOLVED_PENDING — every cell in the true unresolved pending
     * state blocks finalization (overlay_state='NOT_INSPECTED',
     * answered_value_id NULL, not_inspected_reason NULL). This includes
     * unresolved HUMAN_CONFIRMATION cells — no pending cell may survive.
     * Order: response_id.
     */
    private async checkUnresolvedPending(visit: VisitSnapshot): Promise<FinalizationBlocker[]> {
        const rows = await this.db.query(
            `SELECT cr.response_id, cr.item_definition_id, cr.subject_id, d.item_code
               FROM checklist_response cr
               JOIN checklist_item_definition d ON d.item_definition_id = cr.item_definition_id
              WHERE cr.visit_id = ?
                AND cr.overlay_state = 'NOT_INSPECTED'
                AND cr.answered_value_id IS NULL
                AND cr.not_inspected_reason IS NULL
              ORDER BY cr.response_id`,
            [visit.visitId],
        );
        return rows.map((r) =>
            this.blocker(APP_ERR.UNRESOLVED_PENDING, "unresolved-pending", visit.visitId, {
                responseId: Number(r.response_id),
                itemDefinitionId: Number(r.item_definition_id),
                subjectId: r.subject_id === null ? null : Number(r.subject_id),
                itemCode: String(r.item_code),
            }),
        );
    }

    /**
     * 3) E_UNINSPECTED_NEEDS_REASON — every DELIBERATE NOT_INSPECTED cell
     * that will survive into the finalized Visit carries a meaningful
     * (trimmed non-blank) reason. A reason-NULL cell is the unresolved
     * PENDING state and belongs to check 2 (E_UNRESOLVED_PENDING) — it is
     * never double-reported here; only a PRESENT-but-blank reason ('' or
     * whitespace, representable at rest) is a reason blocker. Never
     * auto-filled. Order: response_id.
     */
    private async checkUninspectedReasons(visit: VisitSnapshot): Promise<FinalizationBlocker[]> {
        const rows = await this.db.query(
            `SELECT cr.response_id, cr.item_definition_id, cr.subject_id, cr.not_inspected_reason, d.item_code
               FROM checklist_response cr
               JOIN checklist_item_definition d ON d.item_definition_id = cr.item_definition_id
              WHERE cr.visit_id = ? AND cr.overlay_state = 'NOT_INSPECTED'
              ORDER BY cr.response_id`,
            [visit.visitId],
        );
        const blockers: FinalizationBlocker[] = [];
        for (const r of rows) {
            const reason = r.not_inspected_reason === null ? null : String(r.not_inspected_reason);
            if (reason !== null && normalizeText(reason) === null) {
                blockers.push(
                    this.blocker(APP_ERR.UNINSPECTED_NEEDS_REASON, "blank-not-inspected-reason", visit.visitId, {
                        responseId: Number(r.response_id),
                        itemDefinitionId: Number(r.item_definition_id),
                        subjectId: r.subject_id === null ? null : Number(r.subject_id),
                        itemCode: String(r.item_code),
                    }),
                );
            }
        }
        return blockers;
    }

    /**
     * 4/5) E_NC_UNACCOUNTED + E_NC_NEEDS_NOTE — every answered cell whose
     * selected allowed value has semantic_class='NON_COMPLIANT' must be
     * linked to a Finding AND carry a meaningful note (the §7 note rule,
     * re-checked). T11 never creates/links a Finding and never writes a note.
     * One pass over the NC cells; two distinct blocker codes. Order:
     * response_id.
     */
    private async checkNcCells(visit: VisitSnapshot): Promise<FinalizationBlocker[]> {
        const rows = await this.db.query(
            `SELECT cr.response_id, cr.item_definition_id, cr.subject_id, cr.finding_id, cr.note, d.item_code
               FROM checklist_response cr
               JOIN checklist_item_definition d ON d.item_definition_id = cr.item_definition_id
               JOIN checklist_allowed_value av ON av.allowed_value_id = cr.answered_value_id
              WHERE cr.visit_id = ? AND av.semantic_class = 'NON_COMPLIANT'
              ORDER BY cr.response_id`,
            [visit.visitId],
        );
        const blockers: FinalizationBlocker[] = [];
        for (const r of rows) {
            const base = {
                responseId: Number(r.response_id),
                itemDefinitionId: Number(r.item_definition_id),
                subjectId: r.subject_id === null ? null : Number(r.subject_id),
                itemCode: String(r.item_code),
            };
            // the two §8 requirements are independent: an NC cell may violate
            // either or both (both only under a fabricated read — the schema
            // makes a link-less NC cell unrepresentable at rest)
            if (r.finding_id === null) {
                blockers.push(this.blocker(APP_ERR.NC_UNACCOUNTED, "nc-unaccounted", visit.visitId, base));
            }
            if (normalizeText(r.note === null ? null : String(r.note)) === null) {
                blockers.push(
                    this.blocker(APP_ERR.NC_NEEDS_NOTE, "nc-needs-note", visit.visitId, {
                        ...base,
                        findingId: r.finding_id === null ? null : Number(r.finding_id),
                    }),
                );
            }
        }
        return blockers;
    }

    /**
     * 6) E_CHK012 — the adopted SCHEDULE physical/domain invariants
     * re-checked for every response whose PINNED definition has
     * response_model='SCHEDULE' (generic durable discriminator, never
     * item_code switching). Rows are never mutated here; a finalized state
     * cannot contain a structurally invalid schedule.
     *   a) reconciliation rows belong only to SCHEDULE responses;
     *   b) no overlay state coexists with reconciliation rows;
     *   c) COMPLIANT overall has no discrepancy row (difference <> 0 OR
     *      discrepancy_type NOT NULL);
     *   d) per row: meaningful category; difference == observed - declared;
     *      discrepancy_type NULL or in the closed set; OTHER ⇒ non-blank
     *      discrepancy_desc.
     * Order: response_id, then row_id.
     */
    private async checkScheduleConsistency(visit: VisitSnapshot): Promise<FinalizationBlocker[]> {
        const blockers: FinalizationBlocker[] = [];

        // (a) rows under non-SCHEDULE responses of this Visit (trg_recon_bi
        // makes this unrepresentable at rest; T11 re-checks the invariant)
        const foreignRows = await this.db.query(
            `SELECT er.row_id, er.response_id, cr.item_definition_id, cr.subject_id, d.item_code
               FROM equipment_reconciliation_row er
               JOIN checklist_response cr ON cr.response_id = er.response_id
               JOIN checklist_item_definition d ON d.item_definition_id = cr.item_definition_id
              WHERE cr.visit_id = ? AND d.response_model <> 'SCHEDULE'
              ORDER BY er.row_id`,
            [visit.visitId],
        );
        for (const r of foreignRows) {
            blockers.push(
                this.blocker(APP_ERR.CHK012, "schedule-recon-row-on-non-schedule", visit.visitId, {
                    rowId: Number(r.row_id),
                    responseId: Number(r.response_id),
                    itemDefinitionId: Number(r.item_definition_id),
                    subjectId: r.subject_id === null ? null : Number(r.subject_id),
                    itemCode: String(r.item_code),
                }),
            );
        }

        const scheduleResponses = await this.db.query(
            `SELECT cr.response_id, cr.item_definition_id, cr.subject_id, cr.overlay_state,
                    av.semantic_class AS overall_class, d.item_code
               FROM checklist_response cr
               JOIN checklist_item_definition d ON d.item_definition_id = cr.item_definition_id
               LEFT JOIN checklist_allowed_value av ON av.allowed_value_id = cr.answered_value_id
              WHERE cr.visit_id = ? AND d.response_model = 'SCHEDULE'
              ORDER BY cr.response_id`,
            [visit.visitId],
        );
        for (const resp of scheduleResponses) {
            const responseId = Number(resp.response_id);
            const rows = await this.db.query(
                `SELECT row_id, category, declared_qty, observed_qty, difference, discrepancy_type, discrepancy_desc
                   FROM equipment_reconciliation_row
                  WHERE response_id = ?
                  ORDER BY row_id`,
                [responseId],
            );
            const cell = {
                responseId,
                itemDefinitionId: Number(resp.item_definition_id),
                subjectId: resp.subject_id === null ? null : Number(resp.subject_id),
                itemCode: String(resp.item_code),
            };

            // (b) overlay (NA / NOT_INSPECTED) must never coexist with rows
            if (resp.overlay_state !== null && rows.length > 0) {
                blockers.push(
                    this.blocker(APP_ERR.CHK012, "schedule-overlay-with-rows", visit.visitId, cell),
                );
            }

            const overall = resp.overall_class === null ? null : String(resp.overall_class);
            for (const row of rows) {
                const rowId = Number(row.row_id);
                const category = normalizeText(row.category === null ? null : String(row.category));
                const declared = Number(row.declared_qty);
                const observed = Number(row.observed_qty);
                const difference = Number(row.difference);
                const type = row.discrepancy_type === null ? null : String(row.discrepancy_type);
                const desc = row.discrepancy_desc === null ? null : String(row.discrepancy_desc);

                // (d) per-row adopted invariants (schema CHECKs make the
                // quantity/type arms unrepresentable at rest; re-checked here)
                if (category === null) {
                    blockers.push(
                        this.blocker(APP_ERR.CHK012, "schedule-blank-category", visit.visitId, { ...cell, rowId }),
                    );
                }
                if (difference !== observed - declared) {
                    blockers.push(
                        this.blocker(APP_ERR.CHK012, "schedule-bad-difference", visit.visitId, { ...cell, rowId }),
                    );
                }
                const knownTypes = RECON_DISCREPANCY_TYPES as readonly string[];
                if (type !== null && !knownTypes.includes(type)) {
                    blockers.push(
                        this.blocker(APP_ERR.CHK012, "schedule-bad-discrepancy-type", visit.visitId, { ...cell, rowId }),
                    );
                }
                if (type === "OTHER" && normalizeText(desc) === null) {
                    blockers.push(
                        this.blocker(APP_ERR.CHK012, "schedule-other-missing-desc", visit.visitId, { ...cell, rowId }),
                    );
                }

                // (c) COMPLIANT overall must never carry a discrepancy row
                const isDiscrepancy = difference !== 0 || type !== null;
                if (overall === "COMPLIANT" && isDiscrepancy) {
                    blockers.push(
                        this.blocker(APP_ERR.CHK012, "schedule-compliant-with-discrepancy", visit.visitId, {
                            ...cell,
                            rowId,
                        }),
                    );
                }
            }
        }
        return blockers;
    }

    /**
     * 7) E_ORPHAN_FINDING — a Finding whose origin is this Visit, status
     * 'OPEN', and zero recorded sources across BOTH source tables. VOIDED
     * findings are EXPECTED source-less and are never blockers (Gate 4B);
     * IN_TREATMENT/RESOLVED findings and CorrectiveActions of any status are
     * never blockers either (remediation continues after field-truth
     * finalization). Order: finding_id.
     */
    private async checkOrphanFindings(visit: VisitSnapshot): Promise<FinalizationBlocker[]> {
        const rows = await this.db.query(
            `SELECT f.finding_id
               FROM finding f
              WHERE f.origin_visit_id = ?
                AND f.status = 'OPEN'
                AND NOT EXISTS (SELECT 1 FROM checklist_response cr WHERE cr.finding_id = f.finding_id)
                AND NOT EXISTS (SELECT 1 FROM adhoc_observation o WHERE o.finding_id = f.finding_id)
              ORDER BY f.finding_id`,
            [visit.visitId],
        );
        return rows.map((r) =>
            this.blocker(APP_ERR.ORPHAN_FINDING, "orphan-finding", visit.visitId, {
                findingId: Number(r.finding_id),
            }),
        );
    }

    /** any durable NOT_INSPECTED cell of this Visit ⇒ COMPLETED_WITH_UNINSPECTED. */
    private async anyNotInspected(visit: VisitSnapshot): Promise<boolean> {
        const rows = await this.db.query(
            `SELECT 1 AS x FROM checklist_response WHERE visit_id = ? AND overlay_state = 'NOT_INSPECTED' LIMIT 1`,
            [visit.visitId],
        );
        return rows.length > 0;
    }

    // -- transaction unit -----------------------------------------------------

    /**
     * One explicit BEGIN IMMEDIATE … COMMIT unit. Any throw rolls back:
     * a ZeroRowGuard converges via the durable re-read (B5), a
     * FinalizationBlocked marker surfaces as ONE DomainError carrying every
     * blocker, and anything else propagates. The connection is never left
     * inside a transaction.
     */
    private async runUnit<TApplied extends { kind: "applied" }, TConverged extends { kind: "converged" }>(
        work: () => Promise<TApplied | TConverged>,
        converge: () => Promise<TConverged>,
    ): Promise<TApplied | TConverged> {
        await this.db.beginImmediate();
        try {
            const result = await work();
            await this.db.commit();
            return result;
        } catch (e) {
            try {
                await this.db.rollback();
            } catch {
                // rollback must never mask the original failure
            }
            if (e instanceof ZeroRowGuard) {
                return converge();
            }
            if (e instanceof FinalizationBlocked) {
                const first = e.blockers[0];
                throw new DomainError(first.code, blockedMessage(e.blockers), e.blockers);
            }
            throw e;
        }
    }
}

/** deterministic, machine-readable blocker summary (no Arabic display prose). */
function blockedMessage(blockers: readonly FinalizationBlocker[]): string {
    const visitId = blockers[0].visitId;
    const parts = blockers.map((b) => {
        const ids = [
            b.responseId !== undefined && b.responseId !== null ? `response=${b.responseId}` : "",
            b.itemDefinitionId !== undefined && b.itemDefinitionId !== null ? `definition=${b.itemDefinitionId}` : "",
            b.subjectId !== undefined && b.subjectId !== null ? `subject=${b.subjectId}` : "",
            b.itemCode !== undefined && b.itemCode !== null ? `item=${b.itemCode}` : "",
            b.findingId !== undefined && b.findingId !== null ? `finding=${b.findingId}` : "",
            b.rowId !== undefined && b.rowId !== null ? `recon-row=${b.rowId}` : "",
        ]
            .filter((s) => s.length > 0)
            .join(" ");
        return `${b.code}:${b.kind}${ids.length > 0 ? `(${ids})` : ""}`;
    });
    return (
        `finalizeVisit: visit ${visitId} is blocked from finalization by ${blockers.length} blocker(s): ` +
        parts.join("; ")
    );
}
